[package]
name = "mcap-playground"
version = "0.1.0"
edition = "2024"

[dependencies]
foxglove = "0.15.2"
mcap = "0.23.3"
serde = { version = "1.0.228", features = [ "derive" ] }
serde_json = "1.0.145"
